import { Content } from "./content-interface";

export const contents: Content[] = [
  {
    id: 1,
    title: 'Soft Bears',
    description: 'Soft bears are very silky',
    creator: 'Mitali Productions',
    imgURL: 'https://media.istockphoto.com/id/909772478/photo/brown-teddy-bear-isolated-in-front-of-a-white-background.jpg?s=612x612&w=0&k=20&c=F4252bOrMfRTB8kWm2oM2jlb9JXY08tKCaO5G_ms1Uw=',
    type: 'Fantasy',
    tags: ['Teddy Bears', 'Soft Toys'],
  },
  {
    id: 2,
    title: 'Silky',
    description: 'Very Cute and girl thing',
    creator: 'Nishi Creations',
    imgURL: 'https://www.shutterstock.com/image-photo/soft-toys-childs-bedroom-260nw-236471365.jpg',
    type: 'silk',
    tags: ['Soft Teddy', 'Teddy Bears'],
  },
  {
    id: 3,
    title: 'Woolen Baby',
    description: 'This is a complete pack wool',
    creator: 'R C baba',
    imgURL: 'https://media.istockphoto.com/id/1203062063/photo/the-soft-toy-bunny-sits-on-a-bright-background.jpg?s=612x612&w=0&k=20&c=rcaQ6-4tFnqqAnIOt3Bn5HgXP7sFz0j8bTQ7DwMzXyg=',
    type: 'Silk',
    tags: ['Soft Toys', 'Wuzzy Bears'],
  },
  {
    id: 4,
    title: 'Bear Groups',
    description: 'Will be used as a pack of 3 toys',
    creator: 'D J Productions',
    imgURL: 'https://images.unsplash.com/photo-1613339038444-ca6b1e8eb7b4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGx1c2h8ZW58MHx8MHx8&w=1000&q=80',
    type: 'Fantasy',
    tags: ['Soft Toys', 'Teddy Bears'],
  },
  {
    id: 5,
    title: 'Ant man',
    description: 'A man can be any toy with the blush on it',
    creator: 'Nishi K',
    imgURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcYSMKO6HKT3MGROe5oOmSDq-bv1vjp1wg9A&usqp=CAU',
    type: 'Silk',
    tags: ['Soft Teddy', 'Teddy Bears'],
  },
  {
    id: 6,
    title: 'Dolphin',
    description: 'In one character it was found to be brilliant creature ',
    creator: 'Cruzy Khan',
    imgURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXS9qWmy5I45kkpxavNzcXkWHioDCgZS61Dw&usqp=CAU',
    type: 'Fantacy',
    tags: ['Soft Teddy', 'Dolphins'],
  },
  {
    id: 7,
    title: 'Teddy Teedy',
    description: 'A group of teddies to play with.',
    creator: 'Joe Russo',
    imgURL: 'https://media.istockphoto.com/id/1291681199/photo/teddy-bear-with-a-red-heart-isolated-over-white-background-valentines-day-concept.jpg?b=1&s=170667a&w=0&k=20&c=crfrHx_c848ZwPUgVKF37JGV3c9WSgVAtbBzp4r_E_k=',
    type: '',
    tags: ['Soft Toys', 'Teddy Bears'],
  },
  {
    id: 8,
    title: 'Zexon',
    description: 'Cute new teddy bears trying to support and cheer.',
    creator: 'Dinesh Katudia',
    imgURL: 'https://t3.ftcdn.net/jpg/05/71/49/22/360_F_571492234_iQMyxcAVpFaS1JNczL94nU5OBFdHjd3L.jpg',
    type: '',
    tags: ['Cheer', 'Teddy Bears'],
  },
]
